// <auto-generated />
using System;
using LI.BookService.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LI.BookService.DAL.Migrations
{
    [DbContext(typeof(BookServiceDbContext))]
    [Migration("20211026172330_fff")]
    partial class fff
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LI.BookService.Model.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.BookLiterary", b =>
                {
                    b.Property<int>("BookLiteraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BookLiteraryId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookLiteraries");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("MultiSelect")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.ExchangeList", b =>
                {
                    b.Property<int>("ExchangeListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBoth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OfferList1Id")
                        .HasColumnType("int");

                    b.Property<int?>("OfferList2Id")
                        .HasColumnType("int");

                    b.Property<int>("WishList1Id")
                        .HasColumnType("int");

                    b.Property<int?>("WishList2Id")
                        .HasColumnType("int");

                    b.HasKey("ExchangeListId");

                    b.HasIndex("OfferList1Id");

                    b.HasIndex("OfferList2Id");

                    b.HasIndex("WishList1Id");

                    b.HasIndex("WishList2Id");

                    b.ToTable("ExchangeLists");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.List", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OfferListId")
                        .HasColumnType("int");

                    b.Property<int>("WishListId")
                        .HasColumnType("int");

                    b.HasKey("ListId");

                    b.HasIndex("OfferListId");

                    b.HasIndex("WishListId");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.OfferList", b =>
                {
                    b.Property<int>("OfferListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookLiteraryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("YearPublishing")
                        .HasMaxLength(4)
                        .HasColumnType("datetime2");

                    b.HasKey("OfferListId");

                    b.HasIndex("BookLiteraryId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("OfferLists");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Новый"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "В работе"
                        },
                        new
                        {
                            StatusId = 3,
                            Name = "Закрыто"
                        });
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsStaff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SecondName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.UserAddress", b =>
                {
                    b.Property<int>("UserAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddrApart")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("AddrCity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("AddrHouse")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("AddrIndex")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("AddrSreet")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("AddrStructure")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.UserExchangeList", b =>
                {
                    b.Property<int>("UserExchangeListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExchangeListId")
                        .HasColumnType("int");

                    b.Property<int>("OfferListId")
                        .HasColumnType("int");

                    b.Property<bool>("Receiving")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TrackNumber")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("UserExchangeListId");

                    b.HasIndex("ExchangeListId");

                    b.HasIndex("OfferListId");

                    b.ToTable("UserExchangeLists");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.UserList", b =>
                {
                    b.Property<int>("UserListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<int>("TypeList")
                        .HasColumnType("int");

                    b.HasKey("UserListId");

                    b.ToTable("UserLists");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.UserValueCategory", b =>
                {
                    b.Property<int>("UserValueCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserListId")
                        .HasColumnType("int");

                    b.HasKey("UserValueCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserListId");

                    b.ToTable("UserValueCategories");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.WishList", b =>
                {
                    b.Property<int>("WishListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WishListId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.BookLiterary", b =>
                {
                    b.HasOne("LI.BookService.Model.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.Category", b =>
                {
                    b.HasOne("LI.BookService.Model.Entities.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.ExchangeList", b =>
                {
                    b.HasOne("LI.BookService.Model.Entities.OfferList", "OfferList1")
                        .WithMany()
                        .HasForeignKey("OfferList1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LI.BookService.Model.Entities.OfferList", "OfferList2")
                        .WithMany()
                        .HasForeignKey("OfferList2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LI.BookService.Model.Entities.WishList", "WishList1")
                        .WithMany()
                        .HasForeignKey("WishList1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LI.BookService.Model.Entities.WishList", "WishList2")
                        .WithMany()
                        .HasForeignKey("WishList2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OfferList1");

                    b.Navigation("OfferList2");

                    b.Navigation("WishList1");

                    b.Navigation("WishList2");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.List", b =>
                {
                    b.HasOne("LI.BookService.Model.Entities.OfferList", "OfferList")
                        .WithMany()
                        .HasForeignKey("OfferListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LI.BookService.Model.Entities.WishList", "WishList")
                        .WithMany()
                        .HasForeignKey("WishListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferList");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.OfferList", b =>
                {
                    b.HasOne("LI.BookService.Model.Entities.BookLiterary", "BookLiterary")
                        .WithMany()
                        .HasForeignKey("BookLiteraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LI.BookService.Model.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LI.BookService.Model.Entities.User", "User")
                        .WithMany("OfferLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookLiterary");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.UserAddress", b =>
                {
                    b.HasOne("LI.BookService.Model.Entities.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.UserExchangeList", b =>
                {
                    b.HasOne("LI.BookService.Model.Entities.ExchangeList", "ExchangeList")
                        .WithMany()
                        .HasForeignKey("ExchangeListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LI.BookService.Model.Entities.OfferList", "OfferList")
                        .WithMany()
                        .HasForeignKey("OfferListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeList");

                    b.Navigation("OfferList");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.UserValueCategory", b =>
                {
                    b.HasOne("LI.BookService.Model.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LI.BookService.Model.Entities.UserList", "UserList")
                        .WithMany("UserValueCategories")
                        .HasForeignKey("UserListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.WishList", b =>
                {
                    b.HasOne("LI.BookService.Model.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LI.BookService.Model.Entities.UserAddress", "UserAddress")
                        .WithMany()
                        .HasForeignKey("UserAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LI.BookService.Model.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.User", b =>
                {
                    b.Navigation("OfferLists");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("LI.BookService.Model.Entities.UserList", b =>
                {
                    b.Navigation("UserValueCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
